name: Jest Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 15
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
      - name: Run the tests
        run: |
          yarn test
        env:
          CI: true
          MONGO_URL: mongodb://127.0.0.1:27019
      - uses: gitboard-io/gitboard-action@main
        with:
          username: mythosmystery
          key: ${{ secrets.GITBOARD_KEY}}
