name: Deploy

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PWD }}
          script: ./deploy.sh typenotes-ts-mongo main
