name: Deploy

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PWD }}
          script: ./deploy.sh typenotes-ts-mongo main
      - uses: gitboard-io/gitboard-action@main
        with:
          username: mythosmystery
          key: d42059cb-9ddc-4e0a-a83f-85fee5fef28b
